"""currency added

Revision ID: 0fd44d330712
Revises: 60750ad6297a
Create Date: 2025-09-24 01:18:23.337366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fd44d330712'
down_revision: Union[str, None] = '60750ad6297a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_bid_placed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_bid_skipped', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('bid_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('projects_pkey'))
    )
    # ### end Alembic commands ###
