"""marketplace field added to Project

Revision ID: 98681ab6f076
Revises: 0fd44d330712
Create Date: 2025-10-02 18:06:31.542826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98681ab6f076'
down_revision: Union[str, None] = '0fd44d330712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Створюємо enum тип
    marketplace_enum = sa.Enum('FREELANCEHUNT', 'FREELANCER', name='marketplace')
    marketplace_enum.create(op.get_bind())
    
    # Додаємо колонку з enum типом
    op.add_column('projects', sa.Column('marketplace', marketplace_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Видаляємо колонку
    op.drop_column('projects', 'marketplace')
    
    # Видаляємо enum тип
    marketplace_enum = sa.Enum('FREELANCEHUNT', 'FREELANCER', name='marketplace')
    marketplace_enum.drop(op.get_bind())
    # ### end Alembic commands ###
